basePath: /
definitions:
  dto.OkResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: SignalDash backend API documentation
  title: SignalDash API
  version: "1.0"
paths:
  /api/health:
    get:
      description: Get server health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Show the health status
      tags:
      - api
  /api/indicator:
    get:
      description: crawl tradingview for dxy and insert to db
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.OkResponse'
      summary: crawl financial indicators
      tags:
      - api
swagger: "2.0"
