basePath: /
definitions:
  dto.CreateExchangeRateDiffResponse:
    properties:
      exchange_rate_diff:
        type: string
      strong:
        type: string
    type: object
  dto.ScrapeDollarIndexResponse:
    properties:
      dollar_index:
        type: string
    type: object
info:
  contact: {}
  description: SignalDash backend API documentation
  title: SignalDash API
  version: "1.0"
paths:
  /api/exchange-rate:
    get:
      description: fetch KRW and USDT price and get price diff
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.CreateExchangeRateDiffResponse'
      summary: calculate exchange rate premium
      tags:
      - api
  /api/health:
    get:
      description: Get server health status
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Show the health status
      tags:
      - api
  /api/indicator:
    get:
      description: crawl tradingview for dxy and insert to db
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ScrapeDollarIndexResponse'
      summary: crawl financial indicators
      tags:
      - api
swagger: "2.0"
